# Generated by Django 4.1.6 on 2023-03-13 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(default='', max_length=20)),
                ('DoB', models.DateField()),
                ('gendre', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('state_of_origin', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom')], default='', max_length=10)),
                ('lga_of_origin', models.CharField(default='', max_length=100)),
                ('scheme_name', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('phone_number', models.IntegerField()),
                ('year_of_application', models.CharField(default='', max_length=4)),
                ('profile_pics', models.ImageField(default='', upload_to='profile_pics')),
                ('address', models.TextField(default='', max_length=200)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
